feat(bin): check if a program exists

diff --git a/bin/sync-forks b/bin/sync-forks
--- a/bin/sync-forks
+++ b/bin/sync-forks
@@ -6,6 +6,14 @@
 
 set -e
 
+declare -a dependencies=("gh" "jq")
+
+function check() {
+    for val in ${dependencies[@]}; do
+        command -v $val >/dev/null 2>&1 || { echo >&2 "Error: '$val' could not be found."; exit 1; }
+    done
+}
+
 function authenticate() {
     # authenticate with GitHub CLI
     gh auth login -h github.com
@@ -23,5 +31,6 @@ function update() {
     echo "Update completed."
 }
 
+check
 authenticate
 update
